Update patch set 1
Patch Set 1:

Error: Package: python2-heat-agent-docker-cmd-1.10.0-1.el7.noarch (temp)
Requires: python2-paunch
Error: Package: python2-heat-agent-1.10.0-1.el7.noarch (temp)
Requires: os-apply-config
Error: Package: python2-heat-agent-apply-config-1.10.0-1.el7.noarch (temp)
Requires: os-apply-config

Patch-set: 1
Reviewer: Gerrit User 635 <635@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0